config/routes.rb
STARKupid::Application.routes.draw do
  root to: 'sessions#landing'
  get 'sessions/guest', to: 'sessions#guest', as: 'guest_session'
  namespace :api, defaults: { format: :json } do
    get 'visitors', to: 'visits#index'
    resources :favorites, only: [:index, :create]
    delete 'favorites/:username', to: 'favorites#destroy'
    resources :questions, only: [:index, :show] do
      resources :answered_questions, only: [:create]
    end
    post 'profiles/search', to: 'profiles#search', as: 'profiles_search'
    resources :profiles, except: [:new, :edit] do
      resources :messages, only: [:create]
    end
    resources :messages, only: [:index, :show, :destroy]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # resources :profiles, only: [:new, :create, :update, :index]
  get 'profiles/:username/messages/new', to: 'messages#new', as: 'new_message'
  post 'profiles/:username/messages', to: 'messages#create', as: 'make_message'
  get 'profiles/:username', to: 'profiles#show', as: 'show_profile'
  get 'profiles/:username/edit', to: 'profiles#edit', as: 'edit_profile'
  resources :messages, only: [:index, :show]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  email           :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :username, :session_token, :password_digest, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 6 }
  before_validation :ensure_session_token
  has_one :profile, dependent: :destroy
  has_many :received_messages, class_name: 'Message', foreign_key: :receiver_id
  has_many :sent_messages, class_name: 'Message', foreign_key: :sender_id

  attr_reader :password

  def self.find_by_creds(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    @password = password
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.hex
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # updated
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      signin_user!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class='row'>
  <h1>Sign Up</h1>
  <div class='col-xs-6 col-xs-offset-3'> 
    <form action="<%= session_url %>" method='POST' id='signup'>
      <input 
        type='hidden' 
        name='authenticity_token' 
        value='<%= form_authenticity_token %>'>
      <div class='form-group'>
        <label for='user_email'>Email</label>
        <input
          type='text'
          class='form-control'
          id='user_email'
          name='user[email]'
          value='<%= @user.email %>'>
      </div>
      <div class='form-group'>
        <label for='user_username'>Username</label>
        <input
          type='text'
          class='form-control'
          id='user_username'
          name='user[username]'
          value='<%= @user.username %>'>
      </div>
      <div class='form-group'>
        <label for='user_password'>Password</label>
        <input 
          type='password'
          class='form-control'
          name='user[password]'
          id='user_password'>
      </div>
      <div class='col-xs-5'></div>
      <input class='btn btn-primary form-control' id='signup' type='submit' value='Sign Up'>
    </form>
  </div>
</div>