config/routes.rb
STARKupid::Application.routes.draw do
  root to: 'sessions#landing'
  get 'sessions/guest', to: 'sessions#guest', as: 'guest_session'
  namespace :api, defaults: { format: :json } do
    get 'visitors', to: 'visits#index'
    resources :favorites, only: [:index, :create]
    delete 'favorites/:username', to: 'favorites#destroy'
    resources :questions, only: [:index, :show] do
      resources :answered_questions, only: [:create]
    end
    post 'profiles/search', to: 'profiles#search', as: 'profiles_search'
    resources :profiles, except: [:new, :edit] do
      resources :messages, only: [:create]
    end
    resources :messages, only: [:index, :show, :destroy]
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  # resources :profiles, only: [:new, :create, :update, :index]
  get 'profiles/:username/messages/new', to: 'messages#new', as: 'new_message'
  post 'profiles/:username/messages', to: 'messages#create', as: 'make_message'
  get 'profiles/:username', to: 'profiles#show', as: 'show_profile'
  get 'profiles/:username/edit', to: 'profiles#edit', as: 'edit_profile'
  resources :messages, only: [:index, :show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STARKCupid</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <nav class='navbar navbar-inverse' role='navigation'>
    <div class='container-fluid'>
      <div class='navbar-header'>
        <a href='#' class='navbar-brand'>STARKcupid</a>
      </div>

    <div class='collapse navbar-collapse'>
      <ul class='nav navbar-nav navbar-right'>
      <% if current_user %>
        <script>
          var currentUserUsername = '<%= current_user.username %>';
          $(document).ready( function () {
            Backbone.history.start();
          });
        </script>
        <li>
          <a class='navbar-link search-btn' href='#'>
            <span class='glyphicon glyphicon-search'></span> Search
          </a>
        </li>
        <li class='dropdown'>
          <a class='navbar-right dropdown-toggle' data-toggle='dropdown' href='#'>
            <%= current_user.username %> <b class='caret'></b>
          </a>
          <ul class='dropdown-menu'>
            <li><a href='#/profile/edit' class='dropdown-link'>
              Edit Profile
            </a></li>
            <li>
              <a href='#/profiles/<%= current_user.username %>' 
                class='dropdown-link'>
                View Profile
              </a>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to(
          'Sign Out',
          session_url,
          method: :delete,
          class: 'navbar-link') %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Sign In', new_session_url, class: 'navbar-right navbar-link' %>
        </li>
        <li>
          <%= link_to 'Sign Up', new_user_url, class: 'navbar-right navbar-link' %>
        </li>
      <% end %>
      </ul>
    </div>
    </div>
  </nav>

  <% if current_user %>

    <div id='left-nav'>
      <ul class='nav nav-pills nav-stacked'>
        <li class='left-nav'><a href='#' class='matches'>
          <span class='glyphicon glyphicon-heart'></span> Matches</a></li>
        <li class='left-nav'><a href='#/messages' class='msg-nav'>
          <span class='glyphicon glyphicon-envelope'></span> Messages <span class='hidden glyphicon glyphicon-exclamation-sign'></span></a></li>
        <li class='left-nav'><a href='#/questions'>
          <span class='glyphicon glyphicon-question-sign'></span> Questions</a></li>
        <li class='left-nav'><a href='#/visitors'>
          <span class='glyphicon glyphicon-user'></span> Visitors</a></li>
          <li class='left-nav'><a href='#/favorites'>
          <span class='glyphicon glyphicon-star'></span> Favorites</a></li>
      </ul>
      <div class='text-muted text-center' id='favorites'>
        Drag Here To Add Favorite
      </div>
    </div>
  <% end %>

  <div id='content' class='container-fluid'>

<%= yield %>
  </div>

</body>
</html>